Add Feng Bash Scripts and Slurm Scripts for NERSC
lbl-cbg/metfish pull request #2
Opened 2024-01-25 18:59 UTC by smallfishabc

## Motivation

To prepare the training dataset, PDBs may need to be downloaded/processed from the existing dataset. 

CoDNaS folder stores bash scripts to automatically obtain PDBs and calculate P(r) for **different conformations of the same protein.**

PDB70_NERSC folder stores slrum, bash and python scripts to clean downloaded PDB70 dataset and generate P(r) curve with NERSC.

## How to test the behavior?
```
There is a REAME file in the CoDNaS folder to explain the usage of the scripts.

The slurm file in the PDB70_NERSC folder can be submitted to NERSC with SLURM command sbatch to run the script. 

We need to download and copy all scripts in PDB70_NERSC folder to the root directory of PDB70 database together with PDBs. 

We then need to mkdir for pdb/saxs_r/sequence under the root directory and then submit the job.
```

## Checklist

We may need to combine the Python file under the PDB70_NERSC folder as a function of the metfish package.

2024-01-25 20:07 UTC, ajtritt requested changes
Please rename `Feng_bash_scripts` to something more descriptive, and then move it and `PDB70_NERSC` into a new directory title `scripts`.

2024-01-25 20:07 UTC, ajtritt commented on PDB70_NERSC/PDBtoSeq.py
Please add this to the `metfish` package, and make an entry point [here](https://github.com/lbl-cbg/metfish/blob/48207dedc6fd0c8890f793c3b77d292be0066d07/pyproject.toml#L40)

2024-01-25 20:07 UTC, ajtritt commented on Feng_bash_scripts/CoDNaS_FOXS_RAW_single_conf/full_clean.sh
Can you add a comment at the top describing what this script does?

2024-01-25 20:07 UTC, ajtritt commented on PDB70_NERSC/parallel_PDB70.slurm
> +parallel -j 4 bash fixpdb_pr_parallel.bash -f {} -o . ::: *.pdb
```suggestion
ls  *.pdb | parallel -j 4 bash fixpdb_pr_parallel.bash -f {} -o . :::
```

2024-01-31 20:35 UTC, ajtritt commented on scripts/PDB70_NERSC/fixpdb_pr_parallel_v2.bash
> +   python PDBtoSeq.py  -f "${pdb_loc}/fixed_${filename}" -o "${seq_loc}/${filename}.fasta"
```suggestion
   python PDBtoSeq.py  -f "${pdb_loc}/fixed_${filename}" -o "${seq_loc}/${filename}.fasta" 
   echo ${file} >> complete.txt
```

2024-01-31 20:36 UTC, ajtritt commented on scripts/PDB70_NERSC/fixpdb_pr_parallel_v2.bash
> +if [ -f "$file" ]; then
```suggestion
if [ -f "$file" ]; then
       done=`grep -c ${file} complete.txt`
       if [ "$done" -ne "0" ] ; then
             return
       fi
```

2024-03-08 20:01 UTC, smallfishabc commented
Hi, the slurm and python scripts are ready to review. 
The processed training/testing dataset is stored at /global/cfs/cdirs/m3513/metfish/PDB70_verB_fixed_data with a detailed readme file.
I will continue the data transfer from my scratch to this folder after the NERSC maintenance.

2024-03-11 23:12 UTC, ajtritt approved these changes

2024-03-13 22:51 UTC, merged